# Generated by Django 3.0.7 on 2020-06-06 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0002_auto_20200605_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userperformance',
            name='user_answer',
        ),
        migrations.AlterField(
            model_name='case',
            name='diagnosis',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='case',
            name='history',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='case',
            name='teach_points',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.DeleteModel(
            name='UserAnswer',
        ),
        migrations.DeleteModel(
            name='UserPerformance',
        ),
    ]
