# Generated by Django 3.0.7 on 2020-06-06 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0004_auto_20200605_1737'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='case',
            name='diagnosis',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='case',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='num_questions',
        ),
    ]
