# Generated by Django 3.0.7 on 2020-06-06 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0006_case_diagnosis'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='name',
            field=models.CharField(default='', max_length=250),
        ),
    ]
