# Generated by Django 3.0.7 on 2020-06-06 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0007_case_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='OrganSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=75)),
                ('tutorials', models.ManyToManyField(to='viewer.Tutorial')),
            ],
        ),
    ]
