# Generated by Django 3.0.7 on 2020-06-12 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0008_organsystem_tutorial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='teach_points',
            field=models.TextField(default='', max_length=2000),
        ),
    ]
