# Generated by Django 3.0.7 on 2020-06-12 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0009_auto_20200611_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='history',
            field=models.CharField(default='', max_length=500, verbose_name='clinical history'),
        ),
        migrations.AlterField(
            model_name='case',
            name='name',
            field=models.CharField(default='', max_length=250, verbose_name='case name'),
        ),
        migrations.AlterField(
            model_name='case',
            name='teach_points',
            field=models.TextField(default='', max_length=2000, verbose_name='Teaching Points'),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='text',
            field=models.CharField(default='', max_length=200, verbose_name='diagnosis'),
        ),
    ]
